name: Deploy on the server

on:
  push:
    branches: [ master ]

jobs:
  #build-and-test:
    #runs-on: ubuntu-latest

    #steps:
    #- uses: actions/checkout@v4
     # name: Checkout code

  #  - name: Setting up Python
  #    uses: actions/setup-python@v4
  #    with:
   #     python-version: '3.8'

  #  - name: Installing dependencies
  #    run: |
   #     python -m pip install --upgrade pip
   #     pip install python-dotenv mysql-connector-python python-telegram-bot==13.13 prettytable dotenv

  #  - name: Running unittests
  #    run: |
   #     python -m unittest tests.unit_tests

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Deploying script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /prod/adp-client-bot/
          git pull
          pkill -f python3

